services:
    cfg_link_registry.listener.data_container:
        class: Codefog\LinkRegistryBundle\EventListener\DataContainerListener
        arguments:
            - '@database_connection'
            - '@cfg_link_registry'

    cfg_link_registry.listener.insert_tags:
        class: Codefog\LinkRegistryBundle\EventListener\InsertTagsListener
        arguments:
            - '@cfg_link_registry'
