services:
    codefog_link_registry.listener.data_container:
        class: Codefog\LinkRegistryBundle\EventListener\DataContainerListener
        public: true
        arguments:
            - '@database_connection'
            - '@codefog_link_registry'

    codefog_link_registry.listener.insert_tags:
        class: Codefog\LinkRegistryBundle\EventListener\InsertTagsListener
        public: true
        arguments:
            - '@codefog_link_registry'
