services:
    codefog_link_registry:
        class: Codefog\LinkRegistryBundle\LinkRegistry
        arguments:
            - '@database_connection'
            - '@contao.framework'
            - '@security.token_storage'
            - '%codefog_link_registry.types%'
